language: ruby
rvm:
- 2.1.1
bundler_args: --without kitchen_vagrant
before_install:
- echo -n $EC2_SSH_KEY_CHUNK_{0..25} >> ~/.ssh/id_ec2.base64
- cat ~/.ssh/id_ec2.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_ec2
- gem install bundler --pre
script:
- bundle exec rake travis
after_script:
- bundle exec kitchen destroy
env:
  global:
  - EC2_SSH_KEY_PATH="$HOME/.ssh/id_ec2"
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: iwTZB1ZoJlm0oauQl1iuqVIUTpG4LY5XYalp21UvVtnjZtN8YpaI8D40O7QkGFqAYJuQ0Yd0Bi1mz1rJLNs0ypQUcmmVZ5jfwbCa2eQKkwWPJn5TuxmpxOhtxBfilCLuXZpM4QbhmlFZT6eGxpEH8z/ZDx5MqMdm+93IRuFWH5U=
  - secure: i1RMLjRfUGtpduyXKBG1DDkbc5aArDxUCwNp0yLG6PhG9xLVTfWbWtDEF1XcxQyZV+LMB6AWcDhWtw1CGGL44VAN9unVrxCpnbOmf/9tq43v9WkonLTaPVyxcsSk6xL32B4kcC0tCxH69P5cFQ8cq7U7CUsuD3cJyk7OzKP4KYk=
  - secure: GIWoxtXLGRyEMuJF3qvYptqfxpDN7xQQ6E+hAqjZhnzgQytDMAEPNXvDxSbyYFRrIf9Y/jwOiByAqBxbz5Als1i297PGWyV9+ou7BdIMU7I0Hamnsp9nU4fpeQQn6TBM465RSfWCPk6Prxap6dQfqwtnoorqo0kqEw/sIXSjGpQ=
  - secure: QmeGGeKNMIyf2DWBdNP+9WFGsO7sSR0RA48NuvmWhb9D2KmyITfYNlANisFHkDAHAECveQXOVZbRSg5MBMgk2fXDegRMa1Ae4j6BwaALVDVuRVQWI+F7HcfcgHiGXe33IsFpBWz4Cb4pPgx5fOrWxh2N5Vpe8G7Wrn1Jn0IlQcI=
  - secure: G7YQgKjh/97+oMdzU8/P2he/hrKA8Plq4zdnEGoY/K7+XaHyr/qDKFryPqKsI2d1qL+cCn5IIxeSV89lQEudjkyxuyidpr96mnpxtznJsl4Siw6Bb4MYJLDvT5v7MEdKEulFK78UbSTJnHvuQBGKry/aIQyA5FoCfCd+WNuNvX8=
  - secure: nFbPd807Q2NjBlvWKPi9fvlv6fDC8pnIKNi7+JN4UPI6801EO/SR2mm+GOwYA27tAU1EUjIfM4wTy5YNOS4QtarJHBYNW06Z9JEDJSl5YAuKRC1/YYO+fz336KFP3RXfDDu1S4wW2KmzMM/xVDv1gTfnbqPA4ywMrkUGNYaspUg=
  - secure: GCZe+Q+mDBLZWVFTiVhIVu/QuuFfI35pby65MRA4rMWfiMCaZYVfDMZkzRApiqKmw4THII9y77INfx/kXwl1gVwFQFSTzoPIo9JRSjAyCY+VNZbrYX5w/Wd10zsngtpJgnt1l0R/PEtKfMP/Ce7mRh7rOiX4RRvR4dnlNzBLt+M=
  - secure: hOUUKLVLVSfAJQ/g6s4AthyTY9/0+FXj/vuw7CvGG58J2GewVVfkcjMLzJPG7txpHM2ypeIeqB8QIo+NWKLWtIvTmQCDidprSJDMGPSQj+TuX0FK5dhJ2D4HTmMFkBJ6Z1ntfMHFcJRWYDKBjEH9KaGUgtyEZd32a9gi+SIPMPg=
  - secure: bK8AfK6AwwcU1bmWphxujd5E5uh81cFc40kh7fZ5pZRDkeQuI5u5G4mN82bEctyQeej29KRlh02NYcIuKH39wH0DMUjdrDrFog4t34dc8oNJZCG6G0JhoFkv+PoaY4/54gJ18XazQV3y11B15U7z6g9IwSL/DGHJF1d2x1/1UuQ=
  - secure: hQGP18iOPU2vfY24bvOU0T0PGsymF1q6LFJF0Ab7c01absI+3eNitCAzTa8IC3QyYDAfbha5GiM8qFCtlx6Iw9jFA81u6i0Iakw4yKXQbrdYXEtqKyeSN39CA48QHQIc3KNkpKly6+17TbdX6moOyWkalAkUPJD44LGWvUamJeY=
  - secure: QKq4Gvs6Ru0iSjmVagkWObdiNjg4dV241sNYm8/e1I1uzd1VlFCnxotgnK9NHbshUPRnEELN7qkZzy7z+g5prVUrwK4wNqO2KW8l5lkcp41aHZDmxc/Y/NbMkJ9NvjzfNXmbosGfMslRXAkEMXsDriiCdp2oQ0PfRQvGRxHEb1A=
  - secure: mnU2PYQAb4/bHSWJRlUOhbwwY5Fq4Vo90Dwk6L5s5ksBWptiPl086fsARu3A9z2oLDC8R7IAqhvePp6XxmK/L3LgotPnap8+vBoPOmDdkKn+4hFkOMmPMmgN4cxTVwZR6y2GRTT/jPeDqOuSzCD5egpT+/e+NuH27DN+hh8BQKU=
  - secure: hXsCOKI0AuknDFMZvokpEhTkWvoGT2TumUieiFux/aCSDtiWNmj56gzS1HvRFuhWtXuRHBB6pr3B787ej/f/b+FXLVSpNzKJ3JP33gelsp1XKNHxClLI3sFWMn8tPb8pFPJZP02oxinM6auESrXeK0qP4GG+jzwm8kux6PqSNVY=
  - secure: PnRDRQ12klmMAbi+Jr3cLLe8maXb4tebjD/i1LCkBKmSGI06IBvqrCusYszonU/gkLDTkW7Q5eo4HhTekL7iB3i00o8nEvtHSbZ7S+1anAfxd01MtEGtf/+BOBlwpIyi0Gd5fo3KjRwQDo6FraJ9GwP/ZIG0EtLDWiK0B67+XH8=
  - secure: QHzWVZft2DGZL3OpcR0p33hrxPfN4Rh7OOnUBe9KhYSIJghD09fknwcHqGZCiPWSZjxMdAAH5IkZWkkVK19FVwzLjP2E75BwfrBEISH/K0C+Z4DcBOwKMiRvAnPpyQRG2NXnwkgEepoXytZCa5iQw+JIlIUBpopVT1M52xPwxTY=
  - secure: eBJtyxdqGxoyylwVmMgMbRg+2WNclwDrJ5V9FsFAPM77uemsbP6HZtLPaV4tknigcQFUJge6vzD5x5F4f3041mimIy5YEFmoIu4LGd0LGSyjoTg0KrvD2oF8/X2Vji1pvn4vHcl7oHZRfw//YGXY/BsNRnKR7R8sDyFGpkLMzF8=
  - secure: XW1uSJJ9kqSZ7Y2gtWeAjDiguhlk46liz1LpHk8mhVj20O4HOOGon3UTNov6DEbuidGCLplHyLdVuNgBxrLSVs/RGJg0V1S4fOkm4S6RZMwfHTTrFPnHc5OH+ChWihBslvfU9CBBcsXGti/Gv24X9F8Y7FgysLLyIqbGkN5RJbU=
  - secure: Ks4xguEukshUo0g8ugzV4Riw1nC27JqqbuM37BUjQCXp6ZkVFi+WIo8CmFE7Q3g+d7KfSASsEWk3jVFC+l7tgM79wy0GJ3lj3pDnDF0aaa+uxMPaMgo7sXsboHfOKU3WVvnwv2OzGxN0+llU/AokAGuBaKXmBG5rxizSFIiD3zM=
  - secure: IhMhM147eNpP/UnH0PtMaWBG8arBb6bITNqXihWdBBCQUQ9ruv7d3l2NvLUB9rK1g/LIKk1t802x3MOcHrxkZ55+wVvCDKJ4TqfWtFcDChZF8CaOtDlOsEp2wJjkcdNVqH8BnXctAMbEG5DwpPm1b1CiUUY+uy6MsAx03oAVP7E=
  - secure: ew9iKo+23gWAywxym2SXSjeqLP4R7+oMR1mLkXLYEmGWQDgEE3/87D2u380MiDxhIneh8Zwk96Cx1cZqhDqUnYBuIjmmaNkf+TQUkb3x7SxZ56C3J6qMoiTx3ItwTjspWuzOhdVlhW3fpDApUwQ3crlpMsQ2V2zA33JBlQNfHWo=
  - secure: ndF3pxq4Z8DODBufWbD+TvyJ22f8Q9loIGSDnfTLBW09H/NFfvxIj1C4Loa3xvvsaJA61AdRjuRTSe0SThUGkFYJgs1UVI20t6cYZH07KpA4bu/IHqcPDyuCuB8vtYpB1P1QF4lSoAENYISiK/Dkcz51oR66Ee9RfsW3s64uw9U=
  - secure: DCwriZ1PjGPFqSYolSHGxMuphQwMZnUDiL68U+RFn0IBsLwYiWI19/r9kO9guXbE4y4x82dmCh98upps+rJP/k5oPA/HcBhnhRx2CAsVaLeDx9wYsL9MEAzdDEYpC7d9x27UACzs1rMP9vsOOjKnrGhfr0AC+cs0DAz3o5+83fw=
  - secure: PtCc1SCZs164npH5HhXbdrcKWuzHtoHPIPoqQUXJoURISsCGMBSboxEFPVHmJa4/Ytg35eYNVYX762Qg1MRN8jdpS12ttlCXj3j2TVQq3v+QH5yFRzrA7QuCmPv9v184VXfTUtYeCo+yHpOvjC1ulWTiY+772dJdc8m55/1YvXU=
  - secure: UoFlqi81+pliEylU0nFuJS0Xwx8rVwI9RNckOSFHwpHuHfxsmPj+BQl2NUrPwqk7BQRgkPQYSn7PnBnR5Ep3r5Y9GCIK4g6dR9CcCdJVmY2LHCqR68aI8WegNpaWBwx+BDD1n1NKZ1pJtlk26MgNQ4BbyJyumnZDm55/tqirpgU=
  - secure: nGQBAcop4+gvgWSfQnwdXyjQSYme9XtasJNxmxM0I57xxpFd3pf+hEOFCi/qNYKAl22CWdbdnbKn76FXWWkG7QMIlOPaxRidDhMwKJoHibD8c2mlidDvakZ6MqlzvNPjMfLjjzazzm51Oxsas7xSdoIuq5fBFXm9ojubhNPJ32c=
  - secure: gJha0wXa7sISqOfX+bvelsd3olx9syRKTkpTVcxazJJufyb49eoDnIIBV25/BHibgDeoGkfpzt9ne5dXcfoVKi7WhNoRwtfvYyg8fT5D9cODaQaxeZqHa6e13VGkFA5gybHvAhZD6eIwpWBDU5K/mXb5bX2WpmaXEjUeqnod3A4=
  - secure: j1XLW8mrRsz56EovfvLyfGXRikx8W3hmfWv0lamDisPVj5kCbB5bYQIPrGKA9mBcYqMLJ9xk5f/H8QMvzdPjdY6mkXins1RS6lldm0W/eTK7xgL/alI5pazqOAB8IhFW1SnbKvCTF9AEF7qR1oQ3wJf5ILLag5yhkr4RmZz2I/0=
  - secure: Onokv4eQU4mN71NdzpQzGySXNegyOU1eTebmpXmKkNnAE+2JkUM/v2ZYcsLzayYv3wjhRBOSAgZoLDFVtA0PNyIKOV7TiXsC5APR+OrEzDqS95YdqSV94NhY5mDxgDsTVcHcUfspaPL4/8yPFmfoY1JWMgpbiPLiHozE46i0hEQ=
  - secure: D4+jcXrpb8KKvSj4vLLVVWWjuOo4RTF+PdCNoIY8fwBxGOw9Eml8yvAhcKfSxL70NBoPgy6e9JHFqHSpoKW9/EO/N0GbTt2Js07MYfWL8Ciakrf/np/sc9OCEHsxPp+BeLhzFImMVeuYXrFLnvpkH9Au/RfWPnthuAZhC2CD9e8=
  - secure: VAeTx8JeUBGCNilzLfYWI+AVPZelZazjLm93nkXMx5x9gPewh21e5+G8CcDkg9IewBAVlEfFLxAJ4jtcEqUB3ZUd+j/enTPtJ3a5q/hSHsWMflcVRWyepxBh/W18BhdrrIL+zO6JBfjVeZNpNsnzm+grdaYiyHwLX+zP1W9TQls=
  - secure: KM3IjZ8rJy0BYxrxdsYOxFBwNHX8Cefukl+Aa/6i61yQL1HB7E/hBlvFh7ZrWppN+3O8X0CRF7bzZZNLnSKsTdvAN/QtVNxRPRIvPL4SqV07MlCvzdA8AiRufmBcTiwXwft0Lo2rJm9fuss04huW4Rw2bOH8v94L+8nJYOXZiws=
  matrix:
  - KITCHEN_INSTANCE="default-ubuntu-1204"
notifications:
  email:
  - techops@americanhonors.org
